import inspect
import os
import napkin


def generate_markdown_file(title, src_path):
    name, _ = os.path.splitext(os.path.basename(src_path))
    src_file = name + '.py'
    napkin.generate(output_format='plantuml_png', output_dir='../images')
    text = """# {title}
Following examples are auto-generated by
[demo/{src_file}](demo/{src_file})

""".format(title=title, src_file=src_file)
    for diagram in napkin._collected_seq_diagrams:
        text += """## {name}
![UML result image](images/{image_file})
```python
{src}
```
""".format(src=inspect.getsource(diagram.sd_func),
           name=diagram.name,
           image_file=diagram.name.replace(' ', '%20') + '.png')

    md_file = '../{}.md'.format(name.upper())
    with open(md_file, 'wt') as f:
        f.write(text)
    print('MD file generated : {}'.format(md_file))
